name: _
publish_to: none
environment:
  sdk: ^3.7.0-0
workspace:
  - complete/cli
  - complete/flutter_app
  - complete/server
  - complete/wikipedia_api
  - end/cli
  - dart_steps/step_1
  - dart_steps/step_2
  - dart_steps/step_3
  - dart_steps/step_4
  - dart_steps/step_5
  - dart_steps/step_6
  - dart_steps/step_7
  - dart_steps/step_8
  - dart_steps/step_9
  - dart_steps/step_10
dependencies:
  logging: ^1.3.0
