name: _
publish_to: none
environment:
  sdk: ^3.7.0-0
workspace:
  - dart_steps/complete
  - dart_steps/step_1
  - dart_steps/step_2
  - dart_steps/step_3
  - dart_steps/step_4
  - dart_steps/step_5
  - dart_steps/step_6
  - dart_steps/step_7
  - dart_steps/step_8
  - dart_steps/step_9
  - dart_steps/step_10
  - dart_steps/step_11
  - dart_steps/step_12
  - demos/cli
  - demos/flutter_app
  - demos/server
  - demos/wikipedia_api
  - flutter_steps/complete
