name: step_4
description: A sample command-line application.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.7.0-323.2.beta

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
