name: static_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.8.0-70.0.dev

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  wikipedia_shared:
    path: ../wikipedia_shared

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
