name: cli
description: A sample command-line application.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.8.0-70.0.dev

# Add regular dependencies here.
dependencies:
  command_runner:
    path: ../command_runner
  logging: ^1.3.0
  wikipedia:
    path: ../wikipedia

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
